// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Course.proto

package Course

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Timestamp struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_06dcbc50c02cef66, []int{0}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type CourseModel struct {
	CourseId       int32   `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseName     string  `protobuf:"bytes,2,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	CourseDispName string  `protobuf:"bytes,3,opt,name=course_disp_name,json=courseDispName,proto3" json:"course_disp_name,omitempty"`
	CoursePrice    float32 `protobuf:"fixed32,4,opt,name=course_price,json=coursePrice,proto3" json:"course_price,omitempty"`
	CoursePrice2   float32 `protobuf:"fixed32,5,opt,name=course_price2,json=coursePrice2,proto3" json:"course_price2,omitempty"`
	// @inject_tag: gorm:"type:timestamp"
	Addtime              *Timestamp `protobuf:"bytes,6,opt,name=addtime,proto3" json:"addtime,omitempty" gorm:"type:timestamp"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CourseModel) Reset()         { *m = CourseModel{} }
func (m *CourseModel) String() string { return proto.CompactTextString(m) }
func (*CourseModel) ProtoMessage()    {}
func (*CourseModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_06dcbc50c02cef66, []int{1}
}

func (m *CourseModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseModel.Unmarshal(m, b)
}
func (m *CourseModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseModel.Marshal(b, m, deterministic)
}
func (m *CourseModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseModel.Merge(m, src)
}
func (m *CourseModel) XXX_Size() int {
	return xxx_messageInfo_CourseModel.Size(m)
}
func (m *CourseModel) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseModel.DiscardUnknown(m)
}

var xxx_messageInfo_CourseModel proto.InternalMessageInfo

func (m *CourseModel) GetCourseId() int32 {
	if m != nil {
		return m.CourseId
	}
	return 0
}

func (m *CourseModel) GetCourseName() string {
	if m != nil {
		return m.CourseName
	}
	return ""
}

func (m *CourseModel) GetCourseDispName() string {
	if m != nil {
		return m.CourseDispName
	}
	return ""
}

func (m *CourseModel) GetCoursePrice() float32 {
	if m != nil {
		return m.CoursePrice
	}
	return 0
}

func (m *CourseModel) GetCoursePrice2() float32 {
	if m != nil {
		return m.CoursePrice2
	}
	return 0
}

func (m *CourseModel) GetAddtime() *Timestamp {
	if m != nil {
		return m.Addtime
	}
	return nil
}

type ListRequest struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06dcbc50c02cef66, []int{2}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ListResponse struct {
	Result               []*CourseModel `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06dcbc50c02cef66, []int{3}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetResult() []*CourseModel {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "Course.Timestamp")
	proto.RegisterType((*CourseModel)(nil), "Course.CourseModel")
	proto.RegisterType((*ListRequest)(nil), "Course.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "Course.ListResponse")
}

func init() {
	proto.RegisterFile("Course.proto", fileDescriptor_06dcbc50c02cef66)
}

var fileDescriptor_06dcbc50c02cef66 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcd, 0x4e, 0xb3, 0x40,
	0x14, 0x86, 0x3f, 0xfa, 0xc3, 0x27, 0x07, 0x6a, 0x74, 0x74, 0x41, 0xea, 0xa2, 0x14, 0x37, 0x24,
	0x4d, 0x68, 0x82, 0x1b, 0x8d, 0x4b, 0x7f, 0x12, 0x8d, 0x1a, 0x83, 0xdd, 0x1b, 0x5a, 0x8e, 0xcd,
	0x24, 0xa5, 0x33, 0xce, 0x0c, 0x2e, 0xbc, 0x64, 0xaf, 0xc2, 0x30, 0x33, 0xb4, 0xb8, 0x63, 0x9e,
	0x79, 0x78, 0x0f, 0xef, 0x01, 0x82, 0x1b, 0x56, 0x0b, 0x89, 0x29, 0x17, 0x4c, 0x31, 0xe2, 0x9a,
	0xd3, 0x78, 0xb2, 0x66, 0x6c, 0xbd, 0xc1, 0xb9, 0xa6, 0xcb, 0xfa, 0x63, 0xae, 0x68, 0x85, 0x52,
	0x15, 0x15, 0x37, 0x62, 0x7c, 0x07, 0xde, 0xa2, 0x45, 0xe4, 0x12, 0xbc, 0xdd, 0x7d, 0xe8, 0x44,
	0x4e, 0xe2, 0x67, 0xe3, 0xd4, 0x24, 0xa4, 0x6d, 0x42, 0xba, 0xd3, 0xf3, 0xbd, 0x1c, 0xff, 0x38,
	0xe0, 0x9b, 0x91, 0xcf, 0xac, 0xc4, 0x0d, 0x39, 0x03, 0x6f, 0xa5, 0x8f, 0xef, 0xb4, 0xd4, 0x49,
	0xc3, 0xfc, 0xc0, 0x80, 0x87, 0x92, 0x4c, 0xc0, 0xb7, 0x97, 0xdb, 0xa2, 0xc2, 0xb0, 0x17, 0x39,
	0x89, 0x97, 0x83, 0x41, 0x2f, 0x45, 0x85, 0x24, 0x81, 0x23, 0x2b, 0x94, 0x54, 0x72, 0x63, 0xf5,
	0xb5, 0x75, 0x68, 0xf8, 0x2d, 0x95, 0x5c, 0x9b, 0x53, 0x08, 0xac, 0xc9, 0x05, 0x5d, 0x61, 0x38,
	0x88, 0x9c, 0xa4, 0x97, 0xdb, 0xf8, 0xd7, 0x06, 0x91, 0x73, 0x18, 0x75, 0x95, 0x2c, 0x1c, 0x6a,
	0x27, 0xe8, 0x38, 0x19, 0x99, 0xc1, 0xff, 0xa2, 0x2c, 0x9b, 0x3e, 0xa1, 0xab, 0x7b, 0x1f, 0xa7,
	0x76, 0x9f, 0xfb, 0xba, 0xad, 0x11, 0x4f, 0xc1, 0x7f, 0xa2, 0x52, 0xe5, 0xf8, 0x59, 0xa3, 0x54,
	0x84, 0xc0, 0x40, 0xd2, 0x6f, 0xb4, 0x35, 0xf5, 0x73, 0x7c, 0x0d, 0x81, 0x51, 0x24, 0x67, 0x5b,
	0x89, 0x64, 0x06, 0xae, 0x40, 0x59, 0x6f, 0x54, 0xe8, 0x44, 0xfd, 0xc4, 0xcf, 0x4e, 0xda, 0xf8,
	0xce, 0xd2, 0x72, 0xab, 0x64, 0x8f, 0x30, 0x32, 0xf8, 0x0d, 0xc5, 0x57, 0x53, 0xe1, 0x0a, 0xa0,
	0x49, 0xbb, 0x67, 0x62, 0xc1, 0x38, 0xd9, 0xbd, 0xdb, 0xf9, 0x88, 0xf1, 0xe9, 0x5f, 0x68, 0xc6,
	0xc6, 0xff, 0x96, 0xae, 0xfe, 0x6f, 0x17, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xda, 0xb3, 0xf6,
	0x06, 0x1f, 0x02, 0x00, 0x00,
}
